config/routes.rb
BetWithFriends::Application.routes.draw do

  root "home#index"

  scope "/admin" do

    get 'home', to: 'administration#home', as: 'admin_home'

    get 'matches/:id/result/edit', to: 'administration#edit_match_result', as: 'admin_edit_match_result'
    put 'matches/:id/result', to: 'administration#update_match_result', as: 'admin_update_match_result'

    put 'stages/:stage_id/groups/:group_id/standings' => 'administration#update_standings'

    put 'ranking/edit' => 'administration#edit_ranking'

  end

  get 'matches/:id', to: 'matches#show', as: 'match'

  resources :stages do
    resources :groups do
      get 'matches'
      get 'teams'
      get 'standings' => 'standings#show'
      put 'standings' => 'standings#update'
    end
  end

  resources :teams do
    get 'matches'
  end

  resources :crews do
    get 'users'
  end

  resources :users, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :bets
  end

  get 'authentications/new' => 'authentications#new'
  post 'authentications' => 'authentications#create'

end

app/models/bet.rb
class Bet < ActiveRecord::Base

	# user association
	belongs_to :user
	validates :user, presence: true

	# match association
	belongs_to :match
	validates :match, presence: true

	# result association
	has_one :result, :as => :resultable, :autosave => true, :inverse_of => :resultable
	accepts_nested_attributes_for :result
	default_scope {includes(:result).references(:result).includes(match: [:group, :team_a, :team_b]).references(:match)}

	validate :one_bet_per_match_per_user, on: :create

	# only one bet per match per user is allowed
	def one_bet_per_match_per_user
		existing_bet = Bet.where("user_id = ? AND match_id=?", self.user_id, self.match_id).take
		unless existing_bet.nil?
			errors.add(:match, "Only one bet per match is allowed")
		end
	end

end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
	before_action :set_user, only: [:new, :create, :edit, :update]
  before_action :set_bet, only: [:show, :edit, :update]


  # GET /users/:user_id/bets
  def index
    @user = User.includes(bet: [:result, match:[:group, :team_a, :team_b]]).references(:bet).find(params[:user_id])
    logger.debug "List #{@user.bet.length} bet(s) for user ##{params[:user_id]}"
  end

  # GET /users/:user_id/bets/:id
  def show
    logger.debug "show bet #{@bet.inspect}"
  end


  # GET /users/:user_id/bets/new
  def new
  	@bet = Bet.new
  	@bet.build_result
  end

  # GET /users/:user_id/bets/:id/edit
  def edit
  end

  # POST /users/:user_id/bets
  def create

		@bet = Bet.new(bet_params)
		@bet.user_id = params[:user_id]

		respond_to do |format|
      if @bet.save
        logger.debug "bet created #{@bet.inspect}"
        format.html { redirect_to user_bet_path(@bet.user_id, @bet.id), notice: 'Bet was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
	end

  # PUT/PATCH /users/:user_id/bets/:id
  def update
    respond_to do |format|
      if @bet.update(bet_params_for_update)
        logger.debug "bet updated #{@bet.inspect}"
        format.html { redirect_to user_bet_path(@bet.user_id, @bet.id), notice: 'Bet was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      @bet = Bet.where("user_id = ? and bets.id = ?", params[:user_id], params[:id]).take!
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_params
      params.require(:bet).permit(:match_id, result_attributes: [:score_team_a, :score_team_b])
    end
    # Update does not allow the match to be changed
    def bet_params_for_update
      params.require(:bet).permit(result_attributes: [:score_team_a, :score_team_b])
    end

end

app/helpers/bet_helper.rb
module BetHelper
end

app/views/bets/_form.html.erb
<% if @bet.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this result from being saved:</h2>

    <ul>
    <% @bet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<div class="field">
<% if match_editable %>
  Match : <%= collection_select(:bet, :match_id, Match.order(group_id: :asc), :id, :to_string) %> 
<% else %>
  Match : <%= @bet.match.to_string %>
<% end %>

</div>



<%= f.fields_for :result do |result_form| %>
<div class="field">
  Score team A <%= result_form.number_field :score_team_a %>
</div>

<div class="field">
  Score team B <%= result_form.number_field :score_team_b %>
</div>
<% end %>


<br/>
<div class="actions">
  <%= f.submit %>
</div>

<%= link_to 'Back', user_bets_path(params[:user_id]) %>

app/views/bets/edit.html.erb
<h1>Edit bet #<%= @bet.id %></h1>

<%= form_for(@bet, :url => user_bet_path(@bet.user_id, @bet.id)) do |f| %>
<%= render :partial => "bets/form", :locals=>{:f=>f, :bet=>@bet, :match_editable=>false} %>
<% end %>

app/views/bets/index.html.erb
<h1>Listing bets for <%= @user.name %></h1>

<table>
  <thead>
    <tr>
      <th>Match</th>
      <th>Score team a</th>
      <th>Score team b</th>
      <th>When</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.bet.each do |bet| %>
      <tr>
        <td><%= link_to bet.match_id, match_path(bet.match_id) %></td>
        <td><%= bet.result.score_team_a %></td>
        <td><%= bet.result.score_team_b %></td>
        <td><%= bet.updated_at %></td>
        <td><%= link_to 'Show', user_bet_path(bet.user_id, bet.id) %></td>
        <td><%= link_to 'Edit', edit_user_bet_path(bet.user_id, bet.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New', new_user_bet_path(@user) %> |
<%= link_to 'Back', user_path(@user) %>

app/views/bets/new.html.erb
<h1>New bet for user #<%= @user.name %></h1>

<%= form_for(@bet, :url => user_bets_path(params[:user_id])) do |f| %>
<%= render :partial => "bets/form", :locals=>{:f=>f, :bet=>@bet, :match_editable=>true} %>
<% end %>

app/views/bets/show.html.erb
<h1>Bet for user <strong>XXXXXX</strong></h1>

<div class="field">match : 
<%= link_to match_path(@bet.match.id) do %>
	<%= @bet.match.to_string %>
<% end %>
</div>
<div class="field">score team a : <%= @bet.result.score_team_a %></div>
<div class="field">score team b : <%= @bet.result.score_team_b %></div>
<div class="field">when : <%= @bet.updated_at %></div>

<br/>

<%= link_to 'Back', user_bets_path(params[:user_id]) %>