config/routes.rb
BetWithFriends::Application.routes.draw do

  root "home#index"

  scope "/admin" do

    get 'home', to: 'administration#home', as: 'admin_home'

    get 'matches/:id/result/edit', to: 'administration#edit_match_result', as: 'admin_edit_match_result'
    put 'matches/:id/result', to: 'administration#update_match_result', as: 'admin_update_match_result'

    put 'stages/:stage_id/groups/:group_id/standings' => 'administration#update_standings'

    put 'ranking/edit' => 'administration#edit_ranking'

  end

  get 'matches/:id', to: 'matches#show', as: 'match'

  resources :stages do
    resources :groups do
      get 'matches'
      get 'teams'
      get 'standings' => 'standings#show'
      put 'standings' => 'standings#update'
    end
  end

  resources :teams do
    get 'matches'
  end

  resources :crews do
    get 'users'
  end

  resources :users, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :bets
  end

  get 'authentications/new' => 'authentications#new'
  post 'authentications' => 'authentications#create'

end

app/models/group.rb
class Group < ActiveRecord::Base

	# associations
	belongs_to :stage
	validates :stage, presence: true

	has_many :matches, dependent: :destroy
	has_many :standings, dependent: :destroy, inverse_of: :group

	# validation
	validates :name, presence: true, uniqueness: true

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :teams, :matches, :standings]

  # GET /stages/{stage_id}/groups
  # GET /stages/{stage_id}/groups.json
  def index
    @groups = Group.where(stage_id: params[:stage_id])
    @stage = Stage.find(params[:stage_id])
  end

  # GET /stages/{stage_id}/groups/1
  # GET /stages/{stage_id}/groups/1.json
  def show
  end

  # GET /stages/{stage_id}/groups/new
  def new
    @group = Group.new
    @group.stage_id = params[:stage_id]
  end

  # GET /stages/{stage_id}/groups/1/edit
  def edit
  end

  # POST /stages/{stage_id}/groups
  # POST /stages/{stage_id}/groups.json
  def create
    @group = Group.new(group_params)
    @group.stage_id = params[:stage_id]

    respond_to do |format|
      if @group.save
        format.html { redirect_to stage_path(params[:stage_id]), notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/{stage_id}/groups/1
  # PATCH/PUT /stages/{stage_id}/groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to stage_path(params[:stage_id]), notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to stage_path(params[:stage_id]) }
      format.json { head :no_content }
    end
  end

  # GET /stages/{stage_id}/groups/1/matches
  def matches
     @matches = Match.where("group_id = ?", @group.id)
  end

  # GET /stages/{stage_id}/groups/1/teams
  def teams
    @teams = Team.joins("INNER JOIN matches AS matches ON matches.team_a_id=teams.id OR matches.team_b_id=teams.id").where("matches.group_id = ?", @group.id).distinct
  end

  # GET /stages/{stage_id}/groups/1/standings
  def standings
    @standings = Standing.where(group_id: params[:group_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      if (params[:group_id].present?)
        group_id = params[:group_id]
      else 
        group_id = params[:id]
      end
      @group = Group.where("stage_id = ? and id = ?", params[:stage_id], group_id).take!
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<% if @group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

    <ul>
    <% @group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :stage_id %><br>
  <%=  @group.stage_id %>
</div>
<div class="actions">
  <%= f.submit %>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= form_for(@group, :url => stage_group_path(@group.stage_id, @group.id)) do |f| %>
<%= render :partial => "groups/form", :locals=>{:f=>f, :group=>@group} %>
<% end %>

<%= link_to 'Back', stage_group_path(@group.stage.id, @group.id) %>

app/views/groups/index.html.erb
<h1>Listing groups for stage <%= @stage.name %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, stage_group_path(@stage.id, group.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_stage_group_path(@stage) %>

app/views/groups/matches.html.erb
<h1>Listing matches for group <%= @group.name %></h1>

<% @matches.each do |match| %>
<p><%= link_to match.to_string, match_path(match.id) %></p>
<% end %>

<br/>

<%= link_to 'Back', stage_group_path(params[:stage_id], params[:group_id]) %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= form_for(@group, :url => stage_groups_path(@group.stage_id)) do |f| %>
<%= render :partial => "groups/form", :locals=>{:f=>f, :group=>@group} %>
<% end %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @group.stage_id %>
</p>

<p><%= link_to 'teams',  stage_group_teams_path(@group.stage_id, @group.id) %></p>
<p><%= link_to 'matches',  stage_group_matches_path(@group.stage_id, @group.id) %></p>
<p><%= link_to 'standings',  stage_group_standings_path(@group.stage_id, @group.id) %></p>

<%= link_to 'Edit', edit_stage_group_path(@group.stage_id, @group) %> |
<%= link_to 'Destroy', stage_group_path, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', stage_path(@group.stage_id) %>

app/views/groups/standings.html.erb
<h1>Standings for group <%= @group.name %></h1>

<table border="1">
	<thead>
		<tr>
			<th>Equipe</th>
			<th>Joué</th>
			<th>Gagné</th>
			<th>Nul</th>
			<th>Perdu</th>
			<th>Buts pour</th>
			<th>Buts contre</th>
			<th>Points</th>
		</tr>
	</thead>
	<tbody>
		<% @standings.each do |standing| %>
      <tr>
        <td><%= standing.team.name %></td>
        <td><%= standing.played %></td>
        <td><%= standing.won %></td>
        <td><%= standing.draw %></td>
        <td><%= standing.lost %></td>
        <td><%= standing.goals_for %></td>
        <td><%= standing.goals_against %></td>
        <td><%= standing.points %></td>
      </tr>
    <% end %>
	</tbody>
</table>

<br/>

<%= link_to 'Back', stage_group_path(params[:stage_id], params[:group_id]) %>

app/views/groups/teams.html.erb
<h1>Listing teams for group <%= @group.name %></h1>

<% @teams.each do |team| %>
    <p><%= link_to team.name, team_path(team.id) %></p>
<% end %>

<br/>

<%= link_to 'Back', stage_group_path(params[:stage_id], params[:group_id]) %>