config/routes.rb
BetWithFriends::Application.routes.draw do

  root "home#index"

  scope "/admin" do

    get 'home', to: 'administration#home', as: 'admin_home'

    get 'matches/:id/result/edit', to: 'administration#edit_match_result', as: 'admin_edit_match_result'
    put 'matches/:id/result', to: 'administration#update_match_result', as: 'admin_update_match_result'

    put 'stages/:stage_id/groups/:group_id/standings' => 'administration#update_standings'

    put 'ranking/edit' => 'administration#edit_ranking'

  end

  get 'matches/:id', to: 'matches#show', as: 'match'

  resources :stages do
    resources :groups do
      get 'matches'
      get 'teams'
      get 'standings' => 'standings#show'
      put 'standings' => 'standings#update'
    end
  end

  resources :teams do
    get 'matches'
  end

  resources :crews do
    get 'users'
  end

  resources :users, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :bets
  end

  get 'authentications/new' => 'authentications#new'
  post 'authentications' => 'authentications#create'

end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base

	belongs_to :crew
	default_scope {includes(:crew).references(:crew)}

	has_many :bet, inverse_of: :user

	validates :name, presence: true
	validates :email_address, presence: true, uniqueness: true
	validates :password, confirmation: true
	validate :validates_password

	before_save :handle_password


	# password is required for creation and optional for updating
	def validates_password
		if self.new_record?
			if password.blank?
				errors.add(:password, "is required")
			end
		end
	end

	# if the new password is blank, the old value is unchanged, otherwise, the new password is hashed
	def handle_password
		if self.password.blank?
			self.password = self.password_was
		else 
			self.password = hash_password self.email_address, self.password 
		end
	end

	# hash the password
	def hash_password(email_address, password)
		return Digest::SHA1.base64digest password + "|o|" + email_address
	end

	# return true if the given password is the right one
	def authenticate(given_password)
		hashed_password = hash_password self.email_address, given_password
		return hashed_password == self.password
	end

	# serialize the user so that only important data are kept
	def serialize
		self.password = ""
		return self
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticated_user_required, only: [:show, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_owner, only: [:show, :edit, :update]


  # GET /users/1
  # GET /users/1.json
  def show
    @matches = Match.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user] = @user.serialize
      redirect_to @user
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email_address, :password, :password_confirmation, :crew_id)
    end

    # check that the accessed user is the authenticated one
    def check_owner
      if @user.id != @authenticated_user.id
        render :file => "public/403.html", :status => :forbidden, :layout => false
        return
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :crew_id %><br>
    <%= f.number_field :crew_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Back', @user %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Mon espace</h1>

<h2>Mes informations</h2>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>email_address:</strong>
  <%= @user.email_address %>
</p>
<p>
  <strong>Crew:</strong>
  <% if @user.crew %>
  <%= link_to @user.crew.name, @user.crew %>
  <% end %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %>

<h2>Calendrier</h2>
<% @matches.each do |match| %>
	<p>
			<%= link_to match_path(match.id) do %>
				<%= match.to_string %>
			<% end %>
	</p>
<% end %>

<h2>Mon classement</h2>
<p>Score : 57 points</p>
<p>23 pronostiques effectués</p>
<p>Classement : 23ème / 156 participants</p>
<p><a href="#">Accéder au classement</a></p>


<h2>Mes pronostiques</h2>
<%= link_to 'Bets', user_bets_path(@user) %>

<hr/>



<%= link_to 'Back', root_path %>